W8D1/reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs
  resources :posts, except: [:index]

  resources :posts do 
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create]

end

W8D1/reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord

  validates :title, :description, :moderator, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  # has_many :posts,
  #   foreign_key: :sub_id,
  #   class_name: :Post

  has_many :post_subs,
    inverse_of: :sub

  has_many :posts,
    through: :post_subs,
    source: :post

end

W8D1/reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      redirect_to :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = current_user.subs.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = current_user.subs.find(params[:id])
    if @sub.destroy
      redirect_to subs_url
    else
      flash[:errors] = "No sub found"
      redirect_to subs_url
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

W8D1/reddit/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/reddit/app/views/subs/edit.html.erb
<h1>Edit a Subforum</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="_method" value="patch">

  <label>Title
  <input type="text" name="sub[title]" value="<%=@sub.title%>">
  </label>

  <label>Description
  <input type="text" name="sub[description]" value="<%=@sub.description%>">
  </label>

  <input type="submit" value="Update Sub">

</form>

W8D1/reddit/app/views/subs/index.html.erb
<h1>Sub index</h1>

<ul>
  <%  @subs.each do |sub| %>
    <li><a href="<%=sub_url(sub)%>">  
      <%= sub.title %></a>
    </li>
  <% end %>
</ul>

<br>

<a href="<%=new_sub_url%>">Create New Subforum</a>

W8D1/reddit/app/views/subs/new.html.erb
<h1>Create a New Subforum</h1>

<form action="<%= subs_url %>" method="post">
  <%= auth_token_input %>

  <label>Title
  <input type="text" name="sub[title]" value="<%=@sub.title%>">
  </label>

  <label>Description
  <input type="text" name="sub[description]" value="<%=@sub.description%>">
  </label>

  <input type="submit" value="Create New Sub">

</form>

W8D1/reddit/app/views/subs/show.html.erb
<h1>Subforum Show Page</h1>

<%= @sub.title %> <br>
<%= @sub.description %> <br>
<%= @sub.moderator.username %>
<br> <br>

<h2>Posts for this subforum:</h2>

<ul>
  <% @sub.posts.each do |post| %>
    <li> <%= post.title %> </li>
    <li> <%= post.url %> </li>
    <li> <%= post.content %> </li>

    <form><button type="submit" formaction="<%= edit_post_url(post) %>">Edit Post</button></form>
    <form action="<%= post_url(post)%>" method="post">
      <%= auth_token_input %>
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Delete Post">
    </form>
    <br>
  <% end %>
</ul>

<a href="<%=subs_url%>">All Subs</a> <br>
<a href="<%=edit_sub_url(@sub)%>">Edit Sub</a> <br>
<a href="<%=new_post_url%>">Create New Post</a> <br><br>

<form action="<%=sub_url(@sub)%>" method="post" >
  <%=auth_token_input%>
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete Subforum">
</form>